### ISSUE TITLE
Installation failed - sra toolkit permanently moved

### ISSUE THREAD

**Issue by BrettHoutz** [bionode/bionode-sra#8]
I tried to install bionode-sra and the installation failed when it tried to download sra toolkit (sratoolkit.2.3.5-2-mac64.tar.gz). What it downloads is this html file:

```html <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.3.5-2/sratoolkit.2.3.5-2-mac64.tar.gz">here</a>.</p>
</body></html>
```

For now, i'll manually download the toolkit from the new location and try to continue the installation process from there.

**Comment by amanjeev** [comment]
That error means that you (bionode-sra, actually) are trying to download via the old unsecure (http) url. This was fixed via a PR. https://github.com/bionode/bionode-sra/blob/master/sra/Makefile#L31

It could be that you are using an older version of this package or I think @bmpvieira needs to release a newer version?

**Comment by BrettHoutz** [comment]
I installed from npm today, and the version is 1.0.2. The Makefile that was downloaded still uses http.

Thanks for the quick response!

**Comment by amanjeev** [comment]
No worries! :-) 

I will let @bmpvieira respond.

**Comment by bmpvieira** [comment]
Sorry for taking so long to reply. The latest changes just needed to be published on npm. It should be working now. FYI, you can also install the latest development version by doing:

```bash
git clone git@github.com:bionode/bionode-sra.git
cd bionode-sra
npm link
```
